{
 "title": "FiniA",
 "description": "Implementierung der grundlegenden Jahres- und Kontoübersicht\n(nicht vollständig gedebugged)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "yearAct",
    "label": "Jahr",
    "query": "SELECT DISTINCT YEAR(tbl_transaction.dateValue) AS Year\n          FROM tbl_transaction\n          WHERE YEAR(tbl_transaction.dateValue) <= (YEAR(curdate())+1)\n          ORDER BY YEAR(tbl_transaction.dateValue) DESC"
   },
   {
    "name": "accountAct",
    "label": "Konto",
    "query": "SELECT\nname AS 'Name'\nFROM `tbl_account`\nLEFT JOIN tbl_accountType ON tbl_accountType.id = tbl_account.type\nWHERE tbl_accountType.type = 'Girokonto'\nORDER BY name ASC"
   }
  ]
 },
 "panels": [
  { "title": "Jahresübersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kontostand (Monatsbeginn)",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "dataset": "finia_db",
     "rawSql": "SELECT\r\n  tbl_account.name AS Konto,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}01 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `Januar`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}02 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `Februar`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}03 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `März`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}04 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `April`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}05 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `Mai`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}06 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `Juni`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}07 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `Juli`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}08 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `August`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}09 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `September`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}10 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `Oktober`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}11 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `November`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <  ${yearAct}12 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `Dezember`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) <= ${yearAct}12 THEN view_balances.amountSum ELSE 0 END) + tbl_account.startAmount AS `Jahresbilanz`\r\nFROM view_balances\r\n  RIGHT JOIN tbl_account ON view_balances.accountID = tbl_account.id\r\n  WHERE YEAR(tbl_account.dateStart) <= ${yearAct} AND (YEAR(tbl_account.dateEnd) >= ${yearAct} OR ISNULL(tbl_account.dateEnd)) AND tbl_account.type IN( 1 )\r\n  GROUP BY Konto\r\n  ORDER BY Konto ASC"
    }
   ]
  },
  {
   "title": "Bilanz",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "dataset": "finia_db",
     "rawSql": "SELECT\r\n  tbl_account.name AS Konto,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}01 THEN view_balances.amountSum ELSE 0 END) AS `Januar`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}02 THEN view_balances.amountSum ELSE 0 END) AS `Februar`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}03 THEN view_balances.amountSum ELSE 0 END) AS `März`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}04 THEN view_balances.amountSum ELSE 0 END) AS `April`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}05 THEN view_balances.amountSum ELSE 0 END) AS `Mai`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}06 THEN view_balances.amountSum ELSE 0 END) AS `Juni`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}07 THEN view_balances.amountSum ELSE 0 END) AS `Juli`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}08 THEN view_balances.amountSum ELSE 0 END) AS `August`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}09 THEN view_balances.amountSum ELSE 0 END) AS `September`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}10 THEN view_balances.amountSum ELSE 0 END) AS `Oktober`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}11 THEN view_balances.amountSum ELSE 0 END) AS `November`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM view_balances.dateValue) = ${yearAct}12 THEN view_balances.amountSum ELSE 0 END) AS `Dezember`,\r\n  SUM(CASE WHEN YEAR(view_balances.dateValue) = ${yearAct} THEN view_balances.amountSum ELSE 0 END) AS `Jahresbilanz`\r\nFROM view_balances\r\n  RIGHT JOIN tbl_account ON view_balances.accountID = tbl_account.id\r\n  WHERE YEAR(tbl_account.dateStart) <= ${yearAct} AND (YEAR(tbl_account.dateEnd) >= ${yearAct} OR ISNULL(tbl_account.dateEnd)) AND tbl_account.type IN( 1 )\r\n  GROUP BY Konto\r\n  ORDER BY Konto ASC"
    }
   ]
  },
  {
   "title": "Wertpapiere",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "dataset": "finia_db",
     "rawSql": "WITH\r\n  loc_share AS (\r\n    SELECT\r\n      tbl_share.id AS shareId,\r\n      tbl_share.name AS shareName,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <  ${yearAct}01 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `Januar`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}01 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `Februar`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}02 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `März`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}03 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `April`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}04 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `Mai`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}05 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `Juni`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}06 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `Juli`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}07 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `August`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}08 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `September`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}09 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `Oktober`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}10 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `November`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}11 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `Dezember`,\r\n      SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareTransaction.dateTransaction) <= ${yearAct}12 THEN tbl_shareTransaction.tradingVolume ELSE 0 END) AS `Jahresabschluss`\r\n    FROM tbl_shareTransaction\r\n      RIGHT JOIN tbl_share ON tbl_shareTransaction.share = tbl_share.id\r\n    GROUP BY shareId\r\n    ORDER BY shareId ASC),\r\n  loc_shareHistory AS (\r\n    SELECT\r\n      tbl_shareHistory.share AS shareId,\r\n      tbl_share.name AS shareName,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}12 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}12 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `Januar`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}01 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}01 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `Februar`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}02 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}02 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `März`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}03 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}03 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `April`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}04 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}04 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `Mai`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}05 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}05 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `Juni`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}06 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}06 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `Juli`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}07 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}07 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `August`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}08 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}08 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `September`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}09 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}09 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `Oktober`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}10 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}10 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `November`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}11 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}11 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `Dezember`,\r\n      CASE WHEN EXTRACT(YEAR_MONTH FROM NOW()) > ${yearAct}12 THEN SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM tbl_shareHistory.date) = ${yearAct}12 THEN tbl_shareHistory.amount ELSE 0 END) ELSE dateMax.price END AS `Jahresabschluss`\r\n    FROM tbl_shareHistory\r\n      RIGHT JOIN tbl_share ON tbl_shareHistory.share = tbl_share.id\r\n      INNER JOIN (SELECT\r\n        tbl_shareHistory.share AS shareId,\r\n        tbl_shareHistory.amount AS price,\r\n        MAX(tbl_shareHistory.date) AS date\r\n        FROM tbl_shareHistory\r\n        GROUP BY shareId) AS dateMax ON tbl_shareHistory.Share = dateMax.shareId\r\n        GROUP BY shareId\r\n        ORDER BY shareId ASC),\r\n  loc_dividend AS(\r\n    SELECT\r\n      tbl_share.id AS shareId,\r\n      tbl_share.name AS shareName,\r\n      SUM(tbl_accountingEntry.amount) AS amount\r\n    FROM tbl_shareTransaction\r\n      LEFT JOIN tbl_share ON tbl_shareTransaction.share = tbl_share.id\r\n      LEFT JOIN tbl_accountingEntry ON tbl_shareTransaction.accountingEntry = tbl_accountingEntry.id\r\n    WHERE YEAR(tbl_shareTransaction.dateTransaction) = ${yearAct} AND tbl_shareTransaction.tradingVolume = 0\r\n    GROUP BY shareId\r\n    ORDER BY shareId ASC)\r\n            \r\nSELECT\r\n  tbl_share.name AS Wertpapier,\r\n  loc_share.Januar * loc_shareHistory.Januar AS `Januar`,\r\n  loc_share.Februar * loc_shareHistory.Februar AS `Februar`,\r\n  loc_share.März * loc_shareHistory.März AS `März`,\r\n  loc_share.April * loc_shareHistory.April AS `April`,\r\n  loc_share.Mai * loc_shareHistory.Mai AS `Mai`,\r\n  loc_share.Juni * loc_shareHistory.Juni AS `Juni`,\r\n  loc_share.Juli * loc_shareHistory.Juli AS `Juli`,\r\n  loc_share.August * loc_shareHistory.August AS `August`,\r\n  loc_share.September * loc_shareHistory.September AS `September`,\r\n  loc_share.Oktober * loc_shareHistory.Oktober AS `Oktober`,\r\n  loc_share.November * loc_shareHistory.November AS `November`,\r\n  loc_share.Dezember * loc_shareHistory.Dezember AS `Dezember`,\r\n  loc_share.Jahresabschluss * loc_shareHistory.Jahresabschluss AS `Jahresabschluss`,\r\nCASE WHEN NOT ISNULL(loc_dividend.amount) THEN loc_dividend.amount ELSE 0 END AS `Dividende`\r\nFROM tbl_share\r\n  LEFT JOIN loc_share ON tbl_share.id = loc_share.shareId\r\n  LEFT JOIN loc_shareHistory ON tbl_share.id = loc_shareHistory.shareId\r\n  LEFT JOIN loc_dividend ON tbl_share.id = loc_dividend.shareId\r\nWHERE (loc_share.Januar + loc_share.Februar + loc_share.März + loc_share.April + loc_share.Mai + loc_share.Juni + loc_share.Juli + loc_share.August + loc_share.September + loc_share.Oktober + loc_share.November + loc_share.Dezember + loc_share.Jahresabschluss) > 0\r\nGROUP BY Wertpapier\r\nORDER BY Wertpapier ASC"
    }
   ]
  },
  {
   "title": "Darlehen",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "dataset": "finia_db",
     "rawSql": "WITH\r\n  loc_monthlyBalance AS (\r\n    SELECT\r\n      SUM(tbl_accountingEntry.amount) AS amountSum,\r\n      tbl_accountingEntry.category AS categoryID,\r\n      tbl_transaction.account AS accountID,\r\n      tbl_transaction.dateValue AS dateValue\r\n    FROM tbl_accountingEntry\r\n      LEFT JOIN tbl_transaction ON tbl_accountingEntry.transaction = tbl_transaction.id\r\n      INNER JOIN tbl_loan ON tbl_transaction.account = tbl_loan.account\r\n      LEFT JOIN tbl_account ON tbl_transaction.account = tbl_account.id\r\n      LEFT JOIN tbl_loanSumExclude ON tbl_loan.id = tbl_loanSumExclude.loanId AND tbl_loanSumExclude.category = tbl_accountingEntry.category\r\n    WHERE tbl_loanSumExclude.id IS NULL\r\n    GROUP BY categoryID, accountID, YEAR(tbl_transaction.dateValue), MONTH(tbl_transaction.dateValue)\r\n    ORDER BY accountID ASC, dateValue DESC),\r\n    loc_monthlyIntrest AS (\r\n      SELECT\r\n        SUM(tbl_accountingEntry.amount) AS amountSum,\r\n        tbl_accountingEntry.category AS categoryID,\r\n        tbl_transaction.account AS accountID,\r\n        tbl_transaction.dateValue AS dateValue\r\n      FROM tbl_accountingEntry\r\n        LEFT JOIN tbl_transaction ON tbl_accountingEntry.transaction = tbl_transaction.id\r\n        INNER JOIN tbl_loan ON tbl_transaction.account = tbl_loan.account\r\n        LEFT JOIN tbl_account ON tbl_transaction.account = tbl_account.id\r\n        LEFT JOIN tbl_loan loan2 ON tbl_account.id = loan2.account AND loan2.categoryIntrest = tbl_accountingEntry.category\r\n      WHERE loan2.categoryIntrest IS NOT NULL AND YEAR(tbl_transaction.dateValue) = ${yearAct}\r\n      GROUP BY categoryID, accountID, YEAR(tbl_transaction.dateValue)\r\n      ORDER BY accountID ASC, dateValue DESC)\r\nSELECT\r\n  tbl_account.name AS Darlehen,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}01 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `Januar`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}02 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `Februar`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}03 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `März`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}04 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `April`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}05 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `Mai`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}06 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `Juni`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}07 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `Juli`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}08 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `August`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}09 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `September`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}10 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `Oktober`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}11 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `November`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <  ${yearAct}12 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `Dezember`,\r\n  SUM(CASE WHEN EXTRACT(YEAR_MONTH FROM loc_monthlyBalance.dateValue) <= ${yearAct}12 THEN loc_monthlyBalance.amountSum ELSE 0 END) + tbl_account.startAmount AS `Jahresabschluss`,\r\n  CASE WHEN loc_monthlyIntrest.dateValue IS NOT NULL THEN SIGN(tbl_loan.intrestRate)*ABS(loc_monthlyIntrest.amountSum) ELSE 0 END AS `Zinsen`\r\nFROM tbl_loan, ((tbl_account\r\n  LEFT JOIN loc_monthlyBalance ON tbl_account.id = loc_monthlyBalance.accountID)\r\n  LEFT JOIN loc_monthlyIntrest ON loc_monthlyIntrest.accountID = loc_monthlyBalance.accountID)\r\nWHERE (YEAR(loc_monthlyIntrest.dateValue) = ${yearAct} OR YEAR(loc_monthlyIntrest.dateValue) IS NULL) AND\r\n  YEAR(tbl_account.dateStart) <= ${yearAct} AND\r\n  (YEAR(tbl_account.dateEnd) >= ${yearAct} OR ISNULL(tbl_account.dateEnd)) AND\r\n  tbl_account.id IN(tbl_loan.account)\r\nGROUP BY Darlehen\r\nORDER BY Darlehen ASC"
    }
   ]
  },
  { "title": "Kontoübersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Haben",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "dataset": "finia_db",
     "rawSql": "SELECT\r\n  view_categoryFullname.fullname AS `Kategorie`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 1 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Januar`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 2 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Februar`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 3 THEN `view_balances`.`amountSum` ELSE 0 END) AS `März`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 4 THEN `view_balances`.`amountSum` ELSE 0 END) AS `April`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 5 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Mai`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 6 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Juni`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 7 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Juli`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 8 THEN `view_balances`.`amountSum` ELSE 0 END) AS `August`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 9 THEN `view_balances`.`amountSum` ELSE 0 END) AS `September`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 10 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Oktober`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 11 THEN `view_balances`.`amountSum` ELSE 0 END) AS `November`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 12 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Dezember`,\r\n  SUM(CASE WHEN YEAR(`view_balances`.`dateValue`) = ${yearAct} THEN amountSum ELSE 0 END) AS `Gesamt`\r\nFROM `view_balances`\r\n  LEFT JOIN tbl_account ON tbl_account.id = view_balances.accountID\r\n  LEFT JOIN view_categoryFullname ON view_categoryFullname.id = view_balances.categoryID\r\nWHERE year(`view_balances`.`dateValue`) = ${yearAct} AND tbl_account.name = '${accountAct}' AND amountSum>=0\r\nGROUP BY view_categoryFullname.fullname\r\nORDER BY view_categoryFullname.fullname ASC"
    }
   ]
  },
  {
   "title": "Soll",
   "type": "table",
   "gridPos": { "h": 14, "w": 21, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "dataset": "finia_db",
     "rawSql": "SELECT\r\n  view_categoryFullname.fullname AS `Kategorie`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 1 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Januar`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 2 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Februar`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 3 THEN `view_balances`.`amountSum` ELSE 0 END) AS `März`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 4 THEN `view_balances`.`amountSum` ELSE 0 END) AS `April`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 5 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Mai`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 6 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Juni`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 7 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Juli`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 8 THEN `view_balances`.`amountSum` ELSE 0 END) AS `August`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 9 THEN `view_balances`.`amountSum` ELSE 0 END) AS `September`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 10 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Oktober`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 11 THEN `view_balances`.`amountSum` ELSE 0 END) AS `November`,\r\n  SUM(CASE WHEN MONTH(`view_balances`.`dateValue`) = 12 THEN `view_balances`.`amountSum` ELSE 0 END) AS `Dezember`,\r\n  SUM(CASE WHEN YEAR(`view_balances`.`dateValue`) = ${yearAct} THEN amountSum ELSE 0 END) AS `Gesamt`\r\nFROM `view_balances`\r\n  LEFT JOIN tbl_account ON tbl_account.id = view_balances.accountID\r\n  LEFT JOIN view_categoryFullname ON view_categoryFullname.id = view_balances.categoryID\r\nWHERE year(`view_balances`.`dateValue`) = ${yearAct} AND tbl_account.name = '${accountAct}' AND amountSum<0\r\nGROUP BY view_categoryFullname.fullname\r\nORDER BY view_categoryFullname.fullname ASC"
    }
   ]
  }
 ]
}